# Numpy

Numpy is the core library for scientific computing in python.

## Arrays

In [1]:
import numpy as np

a = np.array([1, 2, 3]) 
print(type(a))          
print(a.shape)          
print(a[0], a[1], a[2]) 
a[0] = 5                
print(a)                

b = np.array([[1,2,3],[4,5,6]]) 
print(b.shape)                 
print(b[0, 0], b[0, 1], b[1, 0]) 

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy provides many functions to create arrays

In [2]:
import numpy as np

a = np.zeros((2,2))  
print(a)             
                    

b = np.ones((1,2))   
print(b)             

c = np.full((2,2), 7)
print(c)             
                    

d = np.eye(2)        
print(d)             
                    

e = np.random.random((2,2)) 
print(e) 

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.51200722 0.93248254]
 [0.29819075 0.39494267]]


## Array Indexing

Similar to Slicing in Lists, Numpy offers the Array Indexing(Slicing) This is interdimensional so we have to specify a slice for each dimension of the array.

In [4]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]

print(a[0, 1]) 
b[0, 0] = 77   
print(a[0, 1])  


row_r1 = a[1, :]   
row_r2 = a[1:2, :] 
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape) 

2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [6]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]]) 

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

print(a[[0, 0], [1, 1]])

print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [5]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)

b = np.array([0, 2, 0, 1])

print(a[np.arange(4), b]) 

a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. 

In [7]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2) 

print(bool_idx)

print(a[bool_idx])

print(a[a > 2]) 

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes

In [8]:
import numpy as np

x = np.array([1, 2]) 
print(x.dtype) 

x = np.array([1.0, 2.0]) 
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)  
print(x.dtype)  

int32
float64
int64


## Array Math

One of my favourite aspects of Numpy is it's Array Math.
You can either use the Operator or the method to do operations such as Addition, Subtraction, Multiplication, Division, Square roots. etc

In [9]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Apart from the basic operations one can also perform product of vectors

In [10]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [11]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [12]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)  
        
print(x.T)
        

v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

This is something I didn't delve a lot in the past but with broadcasting you can do arithmetic operations using arrays of different shapes.

In [13]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) 

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [14]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   
print(vv)                 
y = x + vv
print(y)       

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [15]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v 
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [16]:
v = np.array([1,2,3])
w = np.array([4,5])  

print(np.reshape(v, (3, 1)) * w)

x = np.array([[1,2,3], [4,5,6]])

print(x + v)

print((x.T + w).T)

print(x + np.reshape(w, (2, 1)))

print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
